### ISSUE TITLE
Recheck any typo and grammar in Readme.md

### ISSUE THREAD

**Issue by ryanrw** [Ryan-Willpower/react-index-as-key#1]
I'm not fluent in English that much, so there will be a lot of mistakes I made.

Expected:
Fix any typo and grammatically error you've found.

PS. If what I wrote is wrong, please tell me or make a new PR for that mistake! 🤗

**Comment by chamiduu** [comment]
Can you assign me to this issue? I would love to work on this.

**Comment by ryanrw** [comment]
@chamindujs Sure! 🙏
